name = "AXA"
# avatar = "images/profile.png" # Avatar image. Default to "images/profile.webp".
bio = "Revistă de oceanografie ortodoxă "
company = 'România'
# company = '<a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>'
location = "București"
# alternatives:
# location = "<a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>"
# location = "<a href='https://www.google.com/maps/search/Earth'>Earth</a>"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.

[params]
  #layout = "compact"

[social]
  email = "contact@axaneamului.ro"
  facebook = "yourfacebookusername"
  github = "yourgithubusername"
  twitter = "yourtwitterusername"
  linkedin = "yourlinkedinusername"