baseURL = "https://axaneamului.ro"
title = "AXA"
theme = "hugo-theme-bootstrap"
copyright = "Copyright © {year} AXA. Toate drepturile rezervate."

# Multilingual mode
defaultContentLanguage = "ro"
#defaultContentLanguageInSubdir = true # If you use only one language comment this option
disableLanguages = ["en", "fr", "zh-cn" ,"zh-tw"] # For disable one or more language

# Pagination
paginate = 10
# paginatePath = "page"

# Disqus
disqusShortname = "axaneamului-ro"

# Google analytics
googleAnalytics = "G-ZRM60DS3SB"

enableRobotsTXT = true

enableEmoji = true

# hasCJKLanguage = true # Turn on it if your content contains Chinese/Japanese/Korean Languages.

pygmentsUseClasses = true

[blackfriday]
  hrefTargetBlank = true

[mediaTypes]
  [mediaTypes."application/manifest+json"]
    suffixes = ["json"]

[outputFormats]
  [outputFormats.MANIFEST]
    name = "manifest"
    baseName = "manifest"
    mediaType = "application/manifest+json"

[outputs]
  home = ["HTML", "RSS", "JSON", "MANIFEST"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"
  year = "year"
  month = "month"