[ro]
  languageName = "Română"
  weight = 1
  [ro.params]
    dateFormat = "02-01-2006"
    description = "AXA - Revistă de oceanografie ortodoxă "
    keywords = "Dumnezeu, Neam, Familie, România, AXA, Mihai Eminescu, Axa Neamului"
    [ro.params.archive]
      dateFormat = "2 January"

[en]
  languageName = "English"
  weight = 2

[fr]
  languageName = "Français"
  weight = 3
  [fr.params]
    dateFormat = "02-01-2006"
    description = "Un thème de blog extrêmement rapide, réactif et riche en fonctionnalités pour Hugo"
    keywords = "Hugo, Bootstrap, Thème Blog"

[zh-tw]
  languageName = "繁體中文"
  weight = 4
  [zh-tw.params]
    dateFormat = "2006-01-02"
    description = "一個快速、響應式和功能豐富的 Hugo 博客主題"
    keywords = "Hugo, Bootstrap, 博客主題"
    [zh-tw.params.archive]
      dateFormat = "01-02"

[zh-cn]
  languageName = "简体中文"
  weight = 5
  [zh-cn.params]
    dateFormat = "2006-01-02"
    description = "一个快速、响应式和功能丰富的 Hugo 博客主题"
    keywords = "Hugo, Bootstrap, 博客主题"
    [zh-cn.params.archive]
      dateFormat = "01-02"

